# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Cloudy' do
  # Pods for Cloudy
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'CloudyTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxTest'
    pod 'RxBlocking'
  end

end
